# Generated by Django 4.1.1 on 2022-09-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('parentesco', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('fechaNacimiento', models.DateTimeField()),
            ],
        ),
    ]
